### ISSUE TITLE
NeedIndexError: no matching index found. (500 error)

### ISSUE THREAD

**Issue by hbmartin** [glitchdotcom/WebPutty#38]
I'm getting a 500 error on new install, with this trace in the logs:

Exception on / [GET]
Traceback (most recent call last):
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/ziplibs.zip/ziplibs/flask/app.py", line 876, in wsgi_app
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/ziplibs.zip/ziplibs/flask/app.py", line 695, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/app/views.py", line 95, in index
    return render_template('index.html', sites=sites, new_site_form=site_form, page_form=page_form)
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/ziplibs.zip/ziplibs/flask/templating.py", line 85, in render_template
    context, ctx.app)
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/ziplibs.zip/ziplibs/flask/templating.py", line 69, in _render
    rv = template.render(context)
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/ziplibs.zip/ziplibs/jinja2/environment.py", line 891, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~webputty-haroldmartin/1.361755446768650121/app/templates/index.html", line 1, in <module>
    {% extends 'base.html' %}
NeedIndexError: no matching index found.
The suggested index for this query is:
- kind: Site
  properties:
  - name: users
  - name: name

**Comment by XULRunner42** [comment]
I get almost the same error

```
2012-11-01 11:28:14.568 / 500 83ms 0kb Mozilla/5.0 (Windows NT 6.1; WOW64; rv:16.0) Gecko/20100101 Firefox/16.0

64.128.107.133 - - [01/Nov/2012:11:28:14 -0700] "GET / HTTP/1.1" 500 264 - "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:16.0) Gecko/20100101 Firefox/16.0" "nerdputty.appspot.com" ms=83 cpu_ms=108 cpm_usd=0.000030 instance=00c61b117ce94e6c636bafce04f0441b796e925d

E 2012-11-01 11:28:14.566

Exception on / [GET]
Traceback (most recent call last):
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/ziplibs.zip/ziplibs/flask/app.py", line 876, in wsgi_app
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/ziplibs.zip/ziplibs/flask/app.py", line 695, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/app/views.py", line 97, in index
    return home()
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/app/views.py", line 105, in home
    return render_template('home.html')
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/ziplibs.zip/ziplibs/flask/templating.py", line 85, in render_template
    context, ctx.app)
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/ziplibs.zip/ziplibs/flask/templating.py", line 69, in _render
    rv = template.render(context)
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/ziplibs.zip/ziplibs/jinja2/environment.py", line 891, in render
    return self.environment.handle_exception(exc_info, True)
  File "/base/data/home/apps/s~nerdputty/1.362869224873688122/app/templates/home.html", line 1, in <module>
    {% extends "base.html" %}
NotAllowedError
```

I have managed to work through all of the problems that arise in deployment, it completes with no error, but

Could it have anything to do with my deployment version (python2.7/FreeBSD) is different from the server version (python2.5)?  Google advised me that I might want to migrate to the newer version.

**Comment by tghw** [comment]
You'll need to run the app on your development server at least once and make sure a Site is created. Once I did that, with the updated code, it worked.

**Comment by sebas77** [comment]
Hi,

I have a similar problem, I installed the app and it worked, but since I tried to login, I get a 500 :(

 Exception on / [GET] Traceback (most recent call last): File "/base/data/home/apps/s~gpiwebputty/1.363213122747480000/ziplibs.zip/ziplibs/flask/app.

**Comment by tghw** [comment]
Can you paste the full traceback? Also, did you run it and log in on your development machine before deploying?

**Comment by sebas77** [comment]
I am not sure about what you mean with " run it and log in on your 
development machine". Unluckily I am not a google app expert and I am 
trying to use it just to keep on using webputty
I have followed the 
installation steps on github though.

----Messaggio originale----
Da: 
notifications@github.com
Data: 16/11/2012 21.13
A: "FogCreek/WebPutty"
WebPutty@noreply.github.com
Cc: "sebas77"ssense@tiscali.it
Ogg: Re: 
[WebPutty] NeedIndexError: no matching index found. (500 error) (#38)

Can you paste the full traceback? Also, did you run it and log in on 
your development machine before deploying?

---

Reply to this email 
directly or view it on GitHub:
https://github.
com/FogCreek/WebPutty/issues/38#issuecomment-10460454

Invita i tuoi amici e Tiscali ti premia! Il consiglio di un amico vale più di uno spot in TV. Per ogni nuovo abbonato 30 € di premio per te e per lui! Un amico al mese e parli e navighi sempre gratis: http://freelosophy.tiscali.it/

**Comment by tghw** [comment]
You'll need to start the Google AppEngine Launcher and press "Run". Then, when it has started, press "Browse" to take you to the development site. Once there, log in. This is necessary to generate the indexes for the app.

Obviously, this isn't ideal for a turnkey sort of solution. I'll look into a more automated way of generating the indexes.

**Comment by sebas77** [comment]
Thanks,  I will try asap and let you know

**Comment by sebas77** [comment]
doing so, it worked locally perfectly, but after I deployed it (I did it with the deploy button in the launcher) I got several issue online (missing css,  the app does not work after the login at all)

**Comment by sebas77** [comment]
I have noticed that using the fab deploy I get:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fabric\main.py", line 732, in main
    _args, *_kwargs
  File "C:\Python27\lib\site-packages\fabric\tasks.py", line 345, in execute
    results['<local-only>'] = task.run(_args, *_new_kwargs)
  File "C:\Python27\lib\site-packages\fabric\tasks.py", line 121, in run
    return self.wrapped(_args, *_kwargs)
  File "C:\projects\WebPutty\WebPutty\fabfile.py", line 49, in decorated_func
    return func(_args, *_kwargs)
  File "C:\projects\WebPutty\WebPutty\fabfile.py", line 71, in deploy
    clean_packages(env.deploy_path)
  File "C:\projects\WebPutty\WebPutty\fabfile.py", line 84, in clean_packages
    compress.revert_js_css_hashes(base_path)
  File "C:\projects\WebPutty\WebPutty\compress.py", line 28, in revert_js_css_ha
shes
    popen_results(['git', 'checkout', '--', path])
  File "C:\projects\WebPutty\WebPutty\compress.py", line 158, in popen_results
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 679, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 893, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by sebas77** [comment]
that's weird, even if it failed, now it works online
