### ISSUE TITLE
No module named simplejson

### ISSUE THREAD

**Issue by ever4cyth** [glitchdotcom/WebPutty#46]
./dev_appserver.py webputty/
....
INFO     2013-10-27 22:52:20,088 api_server.py:139] Starting API server at: http://localhost:51803
INFO     2013-10-27 22:52:20,137 dispatcher.py:171] Starting module "default" running at: http://localhost:8080
INFO     2013-10-27 22:52:20,146 admin_server.py:117] Starting admin server at: http://localhost:8000
ERROR    2013-10-27 22:52:21,592 wsgi.py:262] 
Traceback (most recent call last):
  File "/home/magnolia/googleapp/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/magnolia/googleapp/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/magnolia/googleapp/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/home/magnolia/googleapp/webputty/bootstrap.py", line 13, in <module>
    from google.appengine.tools.dev_appserver import HardenedModulesHook
  File "/home/magnolia/googleapp/google/appengine/tools/dev_appserver.py", line 62, in <module>
    import simplejson
ImportError: No module named simplejson

I had simplejson in python path, could anyone point out what the problem is here? Thanks!

**Comment by naiyt** [comment]
Do you have simplejson in your path or json (as it's currently called)? Either way, it would be nice if Google updated the dev_appserver module to fix this.

Personally, I commented out the relevant lines in `bootstrap.py`. According to the comments, it's used for some sort of Jinja debugging in the app, although I haven't had to personally use it at all. It's been working fine for me without `HardenedModulesHook` so far.
